site_name: HIMB Summer Course 2021
site_description: HIMB Summer Course 2021
site_author: Samapriya Roy
site_url: https://github.com/himb-summercourse-2021/himb-summercourse-2021.github.io

# Repository
repo_name: himb-summercourse-2021.github.io
repo_url: https://github.com/himb-summercourse-2021/

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Samapriya Roy'


# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    scheme: default
    primary: teal
    accent: indigo
  font:
    text: Google Sans
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: logo

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samapriya
    - icon: fontawesome/brands/medium
      link: https://medium.com/@samapriyaroy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/samapriyaroy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samapriya

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



# Page tree
nav:
  - Introduction: index.md
  - Planet Imagery: projects/planet-asset.md
  - Image & Image Collections in Earth Engine:
    - Images: projects/img.md
    - Image Collection: projects/imagecollection.md
  - Getting Started:
    - Setting up your Accounts: setup/setup.md
    - Basic Housekeeping and Setup: setup/housekeeping.md
    - Lab space: setup/lab.md
  - Pipelines:
    - Downloading Planet Images: projects/downloading-images.md
    - Getting Images into Google Earth Engine: projects/getting-images-ee.md
  - Working with API(s):
    - Data API: projects/data_api.md
    - Ordersv2 API: projects/orders.md
  - Analytics in Earth Engine:
    - Labs: projects/labs_ee.md
    - Functions in Earth Engine: projects/functions.md
    - Reducers and Charts: projects/reducers.md
    - Edge Detection: projects/edges.md
  # - Datasets and Addons: projects/tools.md
  - Citations: citations.md
  - Contact Us: contact.md
